### PR TITLE
Updated to use 3.5.0.GA (support for x86_64).

### PR DESCRIPTION
**Pull request by zendern**
This in turn requires the module to be built with support for x86_64 so
this also includes all the changes to support that.

Also updated the build.py from the templates that are supplied by
Titanium to make the build work.

### CODE REVIEW

**Comment by zendern** [comment]
I am unaware of how to fix this issue. Currently the only error that I see in the Travis CI logs is this. Both of the IOS and Android builds say that they completed successfully. Anyone with more familiarity with how the travis CI build work and/or what the issue is that would be able to help would be greatly appreciated. 

```
[31m[ERROR] [39m: [31m Could not find all required Titanium Modules:[39m
[31m[ERROR] [39m: [31m    id: ti.flurry	 version: 1.6	 platform: ios,iphone,commonjs	 deploy-type: development[39m
```

**Comment by ingo** [comment]
I'll check again in a little. This happens when there are already prepackaged module versions (in this case, 1.5.0) as part of the repo. Those have been moved to the "releases" tab now.

**Comment by ingo** [comment]
Try removing the .zip files. I think it will build correctly.

**Comment by zendern** [comment]
Simply deleting the zip files looks to have worked. Thanks for the help @ingo !!!!!

**Comment by cdrx** [comment]
Can this be merged?

**Comment by ucf713** [comment]
Is there a pre-built release available with these changes?

**Comment by cdrx** [comment]
https://github.com/zendern/ti.flurry/blob/126e4568f86ea4fdb5494a360932e69dbb4f8f6c/ios/ti.flurry-iphone-1.6.zip

**Comment by ingo** [comment]
Approved. Merging.

**Pull request merged**
